// Generated by CoffeeScript 1.9.1
(function() {
  var MessageRouter;

  MessageRouter = require('./lib/spinredis');

  module.exports = MessageRouter;

}).call(this);

//# sourceMappingURL=index.js.map
